"""
Author: Matthias Steinwendner, 2018

The sequence of triangle numbers is generated by adding the natural numbers. 
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
What is the value of the first triangle number to have over five hundred divisors?
"""

from math import sqrt


def get_number_factors(n):
    num = 1
    for i in range(2, int(sqrt(n)+1)):
        if n % i == 0:
            num += 2
    return num


current = 1
triangular_value = current
while True:
    current += 1
    triangular_value += current
    if get_number_factors(triangular_value) > 500:
        break

print(triangular_value)
